enum 
{
	RADIO_LOCAL = 1,
	RADIO_FACTION,
	RADIO_GANG,
	RADIO_BROADCAST,
	RADIO_DISPATCH
}

enum
{
    DIALOG_REGISTER = 1,
    DIALOG_CONFIRMPASS,
    DIALOG_CARSTORAGE,
    DIALOG_LOGIN,
    DIALOG_GENDER,
    DIALOG_AGE,
    DIALOG_REFERRAL,
    DIALOG_INTERIORS,
    GatePass,
    DIALOG_GRAFFITICOLOR,
    DIALOG_GRAFFITITEXT,
    DIALOG_BUY,
    DIALOG_EDITBUY,
    DIALOG_EDITBUY2,
    DIALOG_BUTCHER,
    
    DIALOG_GIVE,
    DIALOG_AMOUNT,

    DIALOG_VERIFY,
	DIALOG_UNVERIFY,

    DIALOG_REFUND,
    DIALOG_RENTAL,

    ACCOUNT_CREATION,

	DIALOG_TUNING,
	DIALOG_TUNING_2,
	
	DIALOG_MENU_WC,
	DIALOG_EDIT_WC,

    DIALOG_CGAMESADMINMENU,
    DIALOG_CGAMESSELECTPOKER,   
    DIALOG_CGAMESSETUPPOKER,   
    DIALOG_CGAMESCREDITS,    
    DIALOG_CGAMESSETUPPGAME,  
    DIALOG_CGAMESSETUPPGAME2,    
    DIALOG_CGAMESSETUPPGAME3,   
    DIALOG_CGAMESSETUPPGAME4,   
    DIALOG_CGAMESSETUPPGAME5,  
    DIALOG_CGAMESSETUPPGAME6,  
    DIALOG_CGAMESSETUPPGAME7,   
    DIALOG_CGAMESBUYINPOKER,    
    DIALOG_CGAMESCALLPOKER,   
    DIALOG_CGAMESRAISEPOKER,     

    DIALOG_LANDBUILDTYPE,
    DIALOG_LANDBUILD1,
    DIALOG_LANDBUILD2,
    DIALOG_LANDMENU,
    DIALOG_LANDOBJECTMENU,
    DIALOG_LANDOBJECTS,

    // Election System
    DIALOG_ELECTION,
    DIALOG_ELECTION_CANDIDATE,
    DIALOG_ELECTION_DISQUALIFY,
    DIALOG_ELECTION_CANDIDATES,
    DIALOG_ELECTION_STAGE,
    DIALOG_VOTE_ELECTION,

    // Binds System
    mybinds,
    bindaction,
    bindedittype,
    bindeditmsg,

    // Sabong System - Made by justinnn - Discord: justinnn#3670
    ShowCockFightMenu,
    ShowSetFighterMenu1,
    ShowSetFighterMenu2,
    ShowFightTypeSelection,
    ShowChargeMenu,

    DIALOG_RADIO,
    DIALOG_VOICE,

    DIALOG_HELP,
    DIALOG_STATS,
    DIALOG_BUYPARTS,
    DIALOG_DMVRELEASE,

    ANTICHEAT_SETTINGS,
    ANTICHEAT_EDIT_CODE,

    DIALOG_CDINSURBUY,
    DIALOG_CDINSURMENU,


    DIALOG_EDITMOBILE,
    DIALOG_CPOSX,
    DIALOG_CPOSY,
    DIALOG_CPOSZ,
    DIALOG_CROTX,
    DIALOG_CROTY,
    DIALOG_CROTZ,
    DIALOG_CSCALEX,
    DIALOG_CSCALEY,
    DIALOG_CSCALEZ,
    DIALOG_TACKLED,
    DIALOG_OPENINVENTORY,
    PhoneCall,
    DIALOG_ATM,
    FINDPOINTS,
    DIALOG_NEWBIE,
    DIALOG_ATMDEPOSIT,
    DIALOG_ATMWITHDRAW,
    DIALOG_TURFLIST,
    DIALOG_TIKISTORE,
    DIALOG_CHOOSEVOUCHER,
    DIALOG_VIPTOYS,
    DIALOG_PAYCHECK,
    DIALOG_ATM_TRANSFER_ID,
    DIALOG_ATM_TRANSFER_AMOUNT,
    DIALOG_ATM_TRANSFER_INFO,
    DIALOG_PAINTBALL,

    DIALOG_BUYCLOTHES,
    DIALOG_PICKLOAD,
    DIALOG_UNREADTEXTS,
    DIALOG_CHANGEPASS,
    DIALOG_BUYCLOTHINGTYPE,
    DIALOG_BUYCLOTHING,
    DIALOG_CLOTHING,
    DIALOG_CLOTHINGMENU,
    DIALOG_CLOTHINGEDIT,
    DIALOG_CLOTHINGBONE,
    DIALOG_BUYVEHICLE,
    DIALOG_BUYVEHICLE2,
    DIALOG_BUYBOAT,
    DIALOG_BUYAIRCRAFT,
    DIALOG_SPAWNCAR,
    DIALOG_DESPAWNCAR,
    DIALOG_FINDCAR,
    DIALOG_BIZINTERIOR,
    DIALOG_FACTIONLOCKER,
    DIALOG_FACTIONEQUIPMENT,
    DIALOG_FACTIONSKINS,
    DIALOG_HITMANCLOTHES,
    DIALOG_MDC,
    DIALOG_MDCWANTED,
    DIALOG_MDCPLAYER1,
    DIALOG_MDCPLAYER2,
    DIALOG_MDCCHARGES,
    DIALOG_PLAYERLOOKUP,
    DIALOG_VEHICLELOOKUP1,
    DIALOG_VEHICLELOOKUP2,
    DIALOG_FACTIONPAY1,
    DIALOG_FACTIONPAY2,
    DIALOG_SALARY,
    DIALOG_SALARY2,
    DIALOG_PHONEBOOK,
    DIALOG_CREATEZONE,
    DIALOG_KIOSK,
    DIALOG_CBUG,
    DIALOG_CONFIRMZONE,
    DIALOG_MP3PLAYER,
    DIALOG_MP3MUSIC,
    DIALOG_MP3RADIO,
    DIALOG_MP3URL,
    DIALOG_MP3RADIOGENRES,
    DIALOG_MP3RADIOSUBGENRES,
    DIALOG_MP3RADIORESULTS,
    DIALOG_MP3RADIOSEARCH,


    DIALOG_HOSPITAL,
    DIALOG_MECHANIC,

    DIALOG_GCLOTHES,
    DIALOG_GANGSTASH,
    DIALOG_GANGSTASHWEAPONS1,
    DIALOG_GANGSTASHWEAPONS2,
    DIALOG_GANGSTASHDRUGS1,
    DIALOG_GANGSTASHDRUGS2,
    DIALOG_GANGSTASHAMMO1,
    DIALOG_GANGSTASHAMMO2,
    DIALOG_GANGSTASHMATS,
    DIALOG_GANGSTASHCASH,
    DIALOG_GANGDEPOSIT,
    DIALOG_GANGWITHDRAW,
    DIALOG_GANGSKINS,
    DIALOG_GANGFINDCAR,
    DIALOG_GANGPOINTSHOP,
 
    DIALOG_FREENAMECHANGE,
    DIALOG_REGISTER_ACCENT,
    DIALOGID_GUIDE_MAIN,
    DIALOGID_GUIDE_MONEY,
    DIALOGID_GUIDE_GUNS,
    DIALOGID_GUIDE_FACTION,
    DIALOGID_GUIDE_ROLEPLAY,
    DIALOGID_GUIDE_LEVEL,

    DIALOG_BIZMENU,
    DIALOG_bName,
    DIALOG_BIZFEE,
    DIALOG_BIZSAFE,
    DIALOG_WITHDRAW,
    DIALOG_DEPOSIT,
    DIALOG_MESSAGE,
    DIALOG_BIZLOCK,
    DIALOG_NEWBWELCOME,
   	DIALOG_NEXT_STATS,
	DIALOG_PREV_STATS,
    //DIALOG_HELP,
    DIALOG_TOP,
    DIALOG_RULES,
    DIALOG_LOCATE,
    DIALOG_LOCATELIST1,
    DIALOG_LOCATELIST2,
    DIALOG_LOCATELIST3,
    DIALOG_LOCATELISTC,
    /*#if defined Christmas
    #else
        DIALOG_CAROL,
    #endif*/
    DIALOG_CREATEQUIZ,
    DIALOG_DLOCKER,
    DIALOG_DGUN,
    //Taljzed kyutiie
    DIALOG_LOOTING,
    
    DIALOG_EMOTE
}

enum {
    GENDER_MALE = 1,
    GENDER_FEMALE
};

enum
{
    MODEL_SELECTION_LANDOBJECTS,
    MODEL_SELECTION_FURNITURE,
    MODEL_SELECTION_CLOTHING,
    MODEL_SELECTION_CLOTHES,   
    MODEL_SELECTION_COPCLOTHING,
    MODEL_SELECTION_INVENTORY,
    MODEL_SELECTION_CLOTHES1,
}

enum
{
    THREAD_COUNT_FURNITURE,
    SENDDATA_THREAD,
    THREAD_LOOKUP_BANS,       
    THREAD_LOAD_LOCATIONS,
    THREAD_LOOKUP_ACCOUNT,      
    THREAD_ACCOUNT_REGISTER,     
    THREAD_PROCESS_LOGIN,        
    THREAD_COUNT_FLAGS,     
    THREAD_TRACE_IP,             
    THREAD_LIST_CHANGES,         
    THREAD_LIST_HELPERS,         
    THREAD_LOAD_HOUSES,          
    THREAD_LIST_TENANTS,      
    THREAD_LOAD_INVENTORY,   
    THREAD_LOAD_GARAGES,         
    THREAD_LOAD_BUSINESSES,      
    THREAD_LOAD_ENTRANCES,       
    THREAD_LOAD_CLOTHING,        
    THREAD_LOAD_FACTIONS,        
    THREAD_LOAD_FACTIONRANKS,    
    THREAD_LOAD_FACTIONSKINS,    
    THREAD_LOAD_FACTIONPAY,      
    THREAD_LOAD_DIVISIONS,       
    THREAD_LOAD_GANGS,           
    THREAD_LOAD_GANGRANKS,       
    THREAD_LOAD_GANGSKINS,                      
    THREAD_HOUSE_INFORMATION,    
    THREAD_COUNT_TEXTS,          
    THREAD_VIEW_TEXTS,           
    THREAD_LIST_VEHICLES,        
    THREAD_FACTION_ROSTER,       
    THREAD_GANG_ROSTER,          
    THREAD_VIEW_PHONEBOOK,       
    THREAD_LOAD_VEHICLES,        
    THREAD_GANG_INFORMATION,     
    THREAD_OFFLINE_IP,           
    THREAD_CHECK_REFERRAL,       
    THREAD_REWARD_REFERRER,      
    THREAD_LIST_FLAGGED,         
    THREAD_CAR_STORAGE,          
    THREAD_LIST_ADMINS,         
    THREAD_LOAD_ATMS,           
    THREAD_LOAD_LOCKERS,            
    THREAD_LOAD_VENDORS,        
    THREAD_LOAD_ACTORS,             
    THREAD_BUYPARTS,                        
    THREAD_LOAD_GAS_PUMPS,      
    THREAD_DMVRELEASE,          
    THREAD_LOAD_MAP_ICONS,
    THREAD_LOAD_LANDS,
    THREAD_LOAD_LANDOBJECTS,
    THREAD_COUNT_LANDOBJECTS,
    THREAD_SELL_LANDOBJECT,
    THREAD_DUPLICATED_OBJECT,
    THREAD_DUPLICATE_LANDOBJECT,
    THREAD_CLEAR_LANDOBJECTS,
    THREAD_LIST_LANDOBJECTS,
    THREAD_LAND_MAINMENU,
    THREAD_LAND_INFORMATION,
    THREAD_DUPLICATE_LANDOBJ,
    THREAD_UPDATE_LANDLABELS,
    THREAD_LOAD_TURFS,
    THREAD_LOAD_ELECTIONS,
    THREAD_LOAD_DYNAMICDROPS
}

enum
{
    VEHICLE_ENGINE,
    VEHICLE_LIGHTS,
    VEHICLE_ALARM,
    VEHICLE_DOORS,
    VEHICLE_BONNET,
    VEHICLE_BOOT,
    VEHICLE_OBJECTIVE
};

enum
{
    STASH_CAPACITY_CASH,
    STASH_CAPACITY_MATERIALS,
    STASH_CAPACITY_WEED,
    STASH_CAPACITY_COCAINE,
    STASH_CAPACITY_METH,
    STASH_CAPACITY_PAINKILLERS,
    STASH_CAPACITY_HPAMMO,
    STASH_CAPACITY_POISONAMMO,
    STASH_CAPACITY_FMJAMMO,
    STASH_CAPACITY_WEAPONS
};

enum
{
    E_OBJECT_TYPE,
    E_OBJECT_INDEX_ID,
    E_OBJECT_EXTRA_ID,
    E_OBJECT_3DTEXT_ID,
    E_OBJECT_OPENED,
    E_OBJECT_WEAPONID,
    E_OBJECT_AMMO,
    E_OBJECT_FACTION,
    E_OBJECT_X,
    E_OBJECT_Y,
    E_OBJECT_Z

};

enum
{
    E_OBJECT_WEAPON,
    E_OBJECT_LAND,
    E_OBJECT_FURNITURE,
    E_OBJECT_BACKPACK
};

enum
{
    EDIT_OBJECT_PREVIEW,
    EDIT_CLOTHING_PREVIEW,
    EDIT_COP_CLOTHING,
    EDIT_VIPCLOTHING,
    EDIT_CLOTHING,
    EDIT_TYPE_ATM,
    EDIT_TYPE_PREVIEW,
    EDIT_TYPE_FURNITURE,
    EDIT_TYPE_OBJECT,   
    EDIT_VENDOR,
    EDIT_LAND_OBJECT_PREVIEW,
    EDIT_LAND_OBJECT,
    EDIT_LAND_GATE_MOVE
};

enum
{
    DEPLOY_SPIKESTRIP,
    DEPLOY_CONE,
    DEPLOY_ROADBLOCK,
    DEPLOY_BARREL,
    DEPLOY_FLARE
};

enum
{
    BUSINESS_STORE,
    BUSINESS_GUNSHOP,
    BUSINESS_CLOTHES,
    BUSINESS_GYM,
    BUSINESS_RESTAURANT,
    BUSINESS_AGENCY,
    BUSINESS_BARCLUB,
    BUSINESS_DEALERSHIP
};

enum
{
    ILLEGAL_GUNS,
    ILLEGAL_DRUGS,
    ILLEGAL_MATS
};
enum
{
    FACTION_NONE,
    FACTION_POLICE,
    FACTION_MEDIC,
    FACTION_NEWS,
    FACTION_GOVERNMENT,
    FACTION_HITMAN,
    FACTION_FEDERAL,
    FACTION_MECHANIC,
    FACTION_TROOPERS,
    FACTION_ELASBURGER
};

enum
{
    JOB_NONE = -1,
    JOB_PIZZAMAN,
    JOB_COURIER,
    JOB_FISHERMAN, // NOT DONE
    JOB_ARMSDEALER,
    JOB_MINER,
    JOB_TAXIDRIVER,
    JOB_DRUGDEALER,
    JOB_GARBAGEMAN,
    JOB_FARMER,
    JOB_FORKLIFTER,
    JOB_LUMBERJACK,
    JOB_FOODPANDA,
    JOB_HARVESTER,
    JOB_BRINKS,
    JOB_SWEEPER,
    JOB_BUTCHER
};

enum
{
    CHECKPOINT_NONE = 0,
    CHECKPOINT_PIZZA,
    CHECKPOINT_TEST,
    CHECKPOINT_MINING,
    CHECKPOINT_PACKAGE,
    CHECKPOINT_DRUGS,
    CHECKPOINT_HOUSE,
    CHECKPOINT_MISC,
    CHECKPOINT_GARBAGE,
    CHECKPOINT_RETURNGARBAGE,
    CHECKPOINT_RETURN_FARM,
    CHECKPOINT_FORKLIFTER,
    CHECKPOINT_LUMBERJACKRUN,
    CHECKPOINT_FOODPANDA,
    CHECKPOINT_HARVESTER,
    CHECKPOINT_COMSERV,
    CHECKPOINT_BUTCHER1,
	CHECKPOINT_BUTCHER2,
	CHECKPOINT_BUTCHER3,
    LAROUTE,
    RETURN
};

enum
{
    HANGUP_DROPPED,
    HANGUP_USER
};

enum
{
    MUSIC_NONE,
    MUSIC_MP3PLAYER,
    MUSIC_BOOMBOX,
    MUSIC_VEHICLE
};

enum
{
    ITEM_WEAPON,
    ITEM_SELLGUN,
    ITEM_MATERIALS,
    ITEM_WEED,
    ITEM_COCAINE,
    ITEM_METH,
    ITEM_PAINKILLERS,
    ITEM_SEEDS,
    ITEM_EPHEDRINE,
    ITEM_CASH,
    ITEM_HPAMMO,
    ITEM_BACKPACK,
    ITEM_POISONAMMO,
    ITEM_FMJAMMO,
    ITEM_DIRTYMONEY
};

enum
{
    CAPACITY_MATERIALS,
    CAPACITY_WEED,
    CAPACITY_COCAINE,
    CAPACITY_METH,
    CAPACITY_PAINKILLERS,
    CAPACITY_SEEDS,
    CAPACITY_EPHEDRINE,
    CAPACITY_HPAMMO,
    CAPACITY_POISONAMMO,
    CAPACITY_FMJAMMO
};

enum
{
    LIMIT_HOUSES,
    LIMIT_BUSINESSES,
    LIMIT_GARAGES,
    LIMIT_VEHICLES
};



enum
{
    GANGWEAPON_9MM,
    GANGWEAPON_SDPISTOL,
    GANGWEAPON_DEAGLE,
    GANGWEAPON_SHOTGUN,
    GANGWEAPON_SPAS12,
    GANGWEAPON_SAWNOFF,
    GANGWEAPON_TEC9,
    GANGWEAPON_UZI,
    GANGWEAPON_MP5,
    GANGWEAPON_AK47,
    GANGWEAPON_M4,
    GANGWEAPON_RIFLE,
    GANGWEAPON_SNIPER,
    GANGWEAPON_MOLOTOV
};

enum
{
    TAG_NORMAL,
    TAG_ADMIN,
    TAG_HELPER,
    TAG_BANDANA,
    TAG_AFK
};

enum
{
    AMMO_HP,
    AMMO_POISON,
    AMMO_FMJ
};

enum
{
    AMMOTYPE_NORMAL,
    AMMOTYPE_HP,
    AMMOTYPE_POISON,
    AMMOTYPE_FMJ
};

enum
{
    ZONETYPE_LAND = 1,
    ZONETYPE_TURF
};

enum
{
    HOSPITAL_COUNTY = 1,
    HOSPITAL_ALLSAINTS = 2
};

